let successPayment = {
  event: "charge.success",
  data: {
    id: 5031512139,
    domain: "live",
    status: "success",
    reference: "isaAdkKYZnR5nKc5yuwt",
    amount: 1000,
    message: "madePayment",
    gateway_response: "Approved",
    paid_at: "2025-06-05T17:06:06.000Z",
    created_at: "2025-06-05T17:05:42.000Z",
    channel: "mobile_money",
    currency: "KES",
    ip_address: "102.219.208.122",
    metadata: {
      eventId: "2JS6Qtn3r3YzVawWYTok",
      promotionId: "nuxC6VDdUPE2xIUTK7ZU",
      organizerId: "3H4KGDHFgGMexpq3dJspTnz8u9z1",
      referrer: "https://kenyatrails.co.ke/events/2JS6Qtn3r3YzVawWYTok/promote",
    },
    fees_breakdown: { amount: "15", formula: null, type: "paystack" },
    log: null,
    fees: 15,
    fees_split: null,
    authorization: {
      authorization_code: "AUTH_zpviachpwv",
      bin: "075XXX",
      last4: "X650",
      exp_month: "12",
      exp_year: "9999",
      channel: "mobile_money",
      card_type: "",
      bank: "M-PESA",
      country_code: "KE",
      brand: "M-pesa",
      reusable: false,
      signature: null,
      account_name: null,
      receiver_bank_account_number: null,
      receiver_bank: null,
    },
    customer: {
      id: 281009673,
      first_name: "",
      last_name: "",
      email: "kamaun629@gmail.com",
      customer_code: "CUS_p88o26rv2lomr5u",
      phone: "0759155650",
      metadata: {},
      risk_action: "default",
      international_format_phone: null,
    },
    plan: {},
    subaccount: {},
    split: {},
    order_id: null,
    paidAt: "2025-06-05T17:06:06.000Z",
    requested_amount: 1000,
    pos_transaction_data: null,
    source: {
      type: "web",
      source: "checkout",
      entry_point: "request_inline",
      identifier: null,
    },
  },
};
